# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_macchiato"

[[battery.display]]
threshold = 10
discharging_symbol = '󰂃 '
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'
discharging_symbol = '󰂃 '

[c]
symbol = " "

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "
disabled = false
threshold = 75
format = '[$symbol${ram_pct}]($style) '
style = 'bold red'

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[os.symbols]
Arch = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Kali = " "
Linux = " "
Macos = " "
Manjaro = " "
NixOS = " "
OpenBSD = "󰈺 "
Pop = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "

# Palette definitions
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
