[env]
TERM = "tmux-256color"

[selection]
save_to_clipboard = true

[window]
dimensions = { columns = 120, lines = 60}

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
normal = { family = "Hack Nerd Font", style = "Regular"}
size = 14
